import {useEffect,useRef,useState,type ReactNode} from 'react';
import {fresh,reduce,aiAction,observation,isPlayer,seatName,SUITS,symbol,cardName,rankName,sortHand,effective,legalCards,bidValue,failCost,trickWinner,pending,type State,type Action,type Card,type Suit,type Seat} from '../engine/game.ts';
import {REGULARS,regular,MODIFIERS,type RegularId,type Modifier} from '../content/regulars.ts';
import {load,save,pack,unpack,type Campaign} from '../persistence.ts';

function seed(){return crypto.getRandomValues(new Uint32Array(1))[0];}
function initial(){try{const loaded=load();if(loaded)return {...loaded,error:''};}catch{return {state:fresh(seed()),campaign:{nights:0,best:0,metMabel:false},error:'Your previous save could not be read. A fresh night is ready.'};}return {state:fresh(seed()),campaign:{nights:0,best:0,metMabel:false},error:''};}
const compact=(n:number)=>new Intl.NumberFormat('en',{notation:n>=10000?'compact':'standard',maximumFractionDigits:1}).format(n);
const suitName=(s:Suit)=>({S:'spades',C:'clubs',D:'diamonds',H:'hearts'})[s];

function Portrait({id,className=''}:{id:number;className?:string}){return <div className={`portrait portrait-${id} ${className}`} style={{backgroundPosition:`${(id%4)*100/3}% ${Math.floor(id/4)*100}%`}} aria-hidden="true"/>;}
function CardFace({card,onClick,selected=false,disabled=false,compact:small=false,trump}:{card:Card;onClick?:()=>void;selected?:boolean;disabled?:boolean;compact?:boolean;trump?:Suit}){
 const bower=trump&&card.rank===11&&card.suit!==trump&&effective(card,trump)===trump;
 const label=`${cardName(card)}${bower?`, left bower, counts as ${suitName(trump)}`:''}${card.mod?`, ${MODIFIERS[card.mod].name}`:''}`;
 const content=<><span className="card-corner">{rankName(card)}<span>{symbol(card.suit)}</span></span>{!small&&<span className="card-pip">{symbol(card.suit)}</span>}{card.mod&&<span className={`stamp ${card.mod}`}>{MODIFIERS[card.mod].mark}</span>}{bower&&<span className="bower">{symbol(trump!)} trump</span>}</>;
 const cls=`playing-card ${card.suit==='H'||card.suit==='D'?'red':''} ${selected?'selected':''} ${small?'small':''} ${disabled?'unplayable':''}`;
 return onClick?<button className={cls} aria-label={label} aria-pressed={selected} onClick={onClick} disabled={disabled}>{content}</button>:<div className={cls} role="img" aria-label={label}>{content}</div>;
}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);
 return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-labelledby="dialog-title"><div className="modal-head"><h2 id="dialog-title">{title}</h2><button className="close" onClick={onClose} aria-label="Close">×</button></div>{children}</dialog>;
}
export default function App(){
 const [boot]=useState(initial);const [s,setS]=useState(boot.state);const [campaign,setCampaign]=useState<Campaign>(boot.campaign);
 const [error,setError]=useState(boot.error);const [modal,setModal]=useState<string|null>(null);const [selected,setSelected]=useState<string[]>([]);
 const [bidSuit,setBidSuit]=useState<Suit>('H');const [bidTricks,setBidTricks]=useState(6);const [inspect,setInspect]=useState<Seat|null>(null);
 const [speed,setSpeed]=useState(false);const [busy,setBusy]=useState(false);const [enhanceId,setEnhanceId]=useState('H9');const [enhanceMod,setEnhanceMod]=useState<Modifier>('gilt');
 const fileRef=useRef<HTMLInputElement>(null);
 const dispatch=(a:Action)=>{setError('');try{setS(reduce(s,a));setSelected([]);}catch(e){setError(e instanceof Error?e.message:'That action is unavailable.');}};
 useEffect(()=>{try{save(s,campaign);}catch{setError('Saving is unavailable in this browser. Use Export in the menu to keep your night.');}},[s,campaign]);
 useEffect(()=>{
  if(s.phase==='over')setCampaign(c=>({...c,nights:Math.max(c.nights,s.night),best:Math.max(c.best,s.score)}));
 },[s.phase,s.night,s.score]);
 useEffect(()=>{
  const ai=['auction','kitty','play'].includes(s.phase)&&!isPlayer(s.turn);
  const settling=s.phase==='settlement'&&!s.counters.settled;
  if(!ai&&!settling)return;const timeout=setTimeout(()=>{try{setS(reduce(s,settling?{type:'settle'}:aiAction(observation(s))));}catch(e){setError(String(e));}},settling?80:speed?150:650);
  return ()=>clearTimeout(timeout);
 },[s,speed]);
 useEffect(()=>{if(s.phase==='auction'){const possible=SUITS.flatMap(suit=>[6,7,8,9,10].map(tricks=>({tricks,suit}))).filter(b=>!s.bid||bidValue(b)>bidValue(s.bid));if(s.bid&&bidValue({tricks:bidTricks,suit:bidSuit})<=bidValue(s.bid)&&possible.length){const first=possible.sort((a,b)=>bidValue(a)-bidValue(b))[0];setBidTricks(first.tricks);setBidSuit(first.suit);}}},[s.bid,s.phase]);
 const activeSeat:Seat=s.phase==='kitty'||s.phase==='insight'?isPlayer(s.turn)?s.turn:0:isPlayer(s.turn)?s.turn:0;
 const shownSeat=inspect??activeSeat;const otherSeat:Seat=shownSeat===0?2:0;const trump=s.bid?.suit;
 const ourTurn=isPlayer(s.turn);const playable=s.phase==='play'&&ourTurn?legalCards(s.hands[s.turn],s.plays,trump!):[];
 const canSelect=(s.phase==='play'||s.phase==='kitty')&&ourTurn&&shownSeat===s.turn;
 const select=(id:string)=>setSelected(old=>s.phase==='kitty'?(old.includes(id)?old.filter(x=>x!==id):old.length<3?[...old,id]:old):[id]);
 const picked=s.hands.flat().find(c=>c.id===selected[0]);
 const exportSave=()=>{const blob=new Blob([JSON.stringify(pack(s,campaign),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`last-social-club-${s.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const startNew=(same=false)=>{setS(fresh(same?s.seed:seed(),campaign.nights+1));setModal(null);setSelected([]);setInspect(null);};
 const chooseEvent=(choice:'rest'|'ask'|'leave')=>{dispatch({type:'event',choice});if(choice!=='leave')setCampaign(c=>({...c,metMabel:true}));};
 const isTable=['auction','kitty','insight','play','trick'].includes(s.phase);
 const regularId=modal?.startsWith('regular:')?modal.slice(8) as RegularId:null;
 return <main className={`club ${s.insight>=3?'after-hours':''}`}>
  <header className="masthead"><div><h1>THE LAST SOCIAL CLUB</h1><span className="version-chip">FIRST SITTING · v0.1</span></div><button className="menu-button" onClick={()=>setModal('menu')} aria-label="Open menu">☰</button></header>
  <div className="resources"><button onClick={()=>setModal('composure')}><span>COMPOSURE</span><strong>{s.composure}<small>/20</small></strong><i className="nerve"><i style={{width:`${s.composure*5}%`}}/></i></button><div className="money"><span>POCKET</span><strong>£{s.cash}</strong></div><button onClick={()=>setModal('insight')}><span>INSIGHT</span><strong>{s.insight}<small>/3</small></strong><i className="insight-dots">{[1,2,3].map(n=><i key={n} className={s.insight>=n?'lit':''}/>)}</i></button></div>
  {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss">×</button></div>}
  {s.phase==='arrival'?<section className="arrival">
   <div className="opening-art"><Portrait id={0}/><div><p className="eyebrow">NIGHT {String(s.night).padStart(2,'0')}</p><h2>There’s a seat for you.</h2><p>{campaign.metMabel?'Mabel has put your cup out. She remembers how you take it. You never told her.':'The rain has followed you to the door. Someone has already dealt you in.'}</p></div></div>
   <div className="welcome-note"><h3>Three deals. Keep your nerve.</h3><p>Control South and North. Bid for the kitty, or pass and break your rivals’ contract. Choose a Regular to back your partnership.</p><p className="muted">This first sitting is a score challenge. Survive all three deals and see what your build can do.</p></div>
   <div className="starter-grid">{(['bookkeeper','gatekeeper','switchboard','wallflower'] as RegularId[]).map(id=>{const r=regular(id);return <button key={id} className="starter" onClick={()=>dispatch({type:'start',regular:id})}><Portrait id={r.portrait}/><div><span className="tag">{r.tag}</span><h3>{r.name}</h3><p>{r.effect}</p><strong>Take a seat →</strong></div></button>;})}</div>
   <button className="text-button" onClick={()=>setModal('rules')}>New to 500? Read the house rules</button><p className="footer-note">Suited contracts · Your progress saves on this device</p>
  </section>:<>
  <div className="regular-rack" aria-label="Your Regulars">{Array.from({length:5},(_,i)=>{const id=s.regulars[i];return id?<button key={id} className="regular-card" onClick={()=>setModal(`regular:${id}`)}><Portrait id={regular(id).portrait}/><span>{regular(id).short}</span></button>:<div key={i} className="regular-empty" aria-label="Empty Regular slot">+</div>;})}</div>
  {isTable&&<>
   <section className="partner-hand"><button className="hand-label" onClick={()=>{setInspect(otherSeat);setSelected([]);}}>{seatName(otherSeat).toUpperCase()} · YOUR {otherSeat===2?'PARTNER':'HAND'} <span>Inspect ↗</span></button><div className="compact-hand">{sortHand(s.hands[otherSeat],trump).map(c=><CardFace key={c.id} card={c} compact trump={trump} onClick={()=>{setInspect(otherSeat);setSelected([]);}}/>)}</div></section>
   <section className="table" aria-label="Playing table">
    <div className={`rival left ${s.turn===3?'acting':''}`}><Portrait id={2}/><strong>MABEL</strong><span>Cautious</span><div className="card-backs">{[0,1,2].map(i=><i key={i}/>)}</div></div>
    <div className={`rival right ${s.turn===1?'acting':''}`}><Portrait id={3}/><strong>ARTHUR</strong><span>Bold</span><div className="card-backs">{[0,1,2].map(i=><i key={i}/>)}</div></div>
    <div className="table-centre">
     {s.phase==='auction'?<><div className="kitty-backs"><i/><i/><i/></div><span className="table-caption">KITTY · 1+ marked card</span><div className="contract-plaque">{s.bid?<>{seatName(s.bid.seat).toUpperCase()} BIDS <b>{s.bid.tricks}{symbol(s.bid.suit)}</b></>:'THE AUCTION IS OPEN'}</div></>:s.phase==='kitty'||s.phase==='insight'?<><p className="table-caption">{seatName(s.bid!.seat).toUpperCase()} TAKES THE KITTY</p><div className="contract-plaque"><b>{s.bid!.tricks}{symbol(trump!)}</b> CONTRACT</div><p className="table-caption">{ourTurn?'Keep ten. Leave three.':'Choosing three discards…'}</p></>:<><div className="contract-mini">{seatName(s.bid!.seat)} · {s.bid!.tricks}{symbol(trump!)} <span>{isPlayer(s.bid!.seat)?'Your contract':'You defend'}</span></div><div className="trick-cards">{s.plays.length?s.plays.map(p=><div key={p.seat} className={`trick-play seat-${p.seat}`}><CardFace card={p.card} trump={trump}/><small>{seatName(p.seat)}</small></div>):<span className="empty-trick">{seatName(s.turn)} leads</span>}</div></>}
    </div><div className="mug" aria-hidden="true"/>
    <div className="table-bottom">{s.phase==='trick'?<strong>{seatName(trickWinner(s.plays,trump!))} wins the trick</strong>:<strong>{ourTurn?'YOUR TURN':'THINKING'} · {seatName(s.turn).toUpperCase()}</strong>}{s.phase!=='auction'&&<span>Tricks · You {s.tricks[0]} : {s.tricks[1]} Rivals</span>}</div>
   </section>
   <section className="active-hand"><div className="hand-label">{seatName(shownSeat).toUpperCase()} · {s.phase==='kitty'&&s.turn===shownSeat?'CHOOSE 3 TO DISCARD':'YOUR HAND'}{inspect!==null&&inspect!==activeSeat?<button onClick={()=>{setInspect(null);setSelected([]);}}>Back to turn ↩</button>:<span>{s.hands[shownSeat].length} cards</span>}</div><div className={`full-hand ${s.hands[shownSeat].length>10?'kitty-hand':''}`}>{sortHand(s.hands[shownSeat],trump).map(c=><CardFace key={c.id} card={c} trump={trump} onClick={canSelect?()=>select(c.id):()=>setModal(`card:${c.id}`)} selected={selected.includes(c.id)} disabled={canSelect&&s.phase==='play'&&!playable.some(p=>p.id===c.id)}/>)}</div></section>
   <div className="score-strip"><span>Deal {s.deal} / 3</span><button onClick={()=>setModal('ledger')}>Score {compact(s.score)} · Pending {compact(pending(s))} ↗</button></div>
   <section className="action-panel" aria-live="polite">
    {s.phase==='auction'&&ourTurn?<><h2>{s.bid?'RAISE TO':'OPEN WITH'} {bidTricks}<span className={bidSuit==='D'||bidSuit==='H'?'red-text':''}>{symbol(bidSuit)}</span></h2><div className="bid-select"><div className="suit-picker">{SUITS.map(suit=><button key={suit} className={`${bidSuit===suit?'chosen':''} ${suit==='D'||suit==='H'?'red-text':''}`} aria-label={suitName(suit)} aria-pressed={bidSuit===suit} onClick={()=>setBidSuit(suit)}>{symbol(suit)}</button>)}</div><div className="quantity"><button disabled={bidTricks<=6} onClick={()=>setBidTricks(n=>n-1)} aria-label="Bid fewer tricks">−</button><strong>{bidTricks}</strong><button disabled={bidTricks>=10} onClick={()=>setBidTricks(n=>n+1)} aria-label="Bid more tricks">+</button></div></div><p className="stakes">Make +{bidValue({tricks:bidTricks,suit:bidSuit})} points · Fail −{failCost(s,{seat:s.turn,tricks:bidTricks,suit:bidSuit})} Composure</p><div className="actions"><button onClick={()=>dispatch({type:'pass'})}>PASS</button><button className="primary" disabled={!!s.bid&&bidValue({tricks:bidTricks,suit:bidSuit})<=bidValue(s.bid)} onClick={()=>dispatch({type:'bid',tricks:bidTricks,suit:bidSuit})}>BID {bidTricks}{symbol(bidSuit)}</button></div>{s.bid&&bidValue({tricks:bidTricks,suit:bidSuit})<=bidValue(s.bid)&&<p className="hint">Choose a bid above {s.bid.tricks}{symbol(s.bid.suit)}, or pass.</p>}</>:null}
    {s.phase==='kitty'&&ourTurn&&<><p>{selected.length} / 3 discards selected</p><button className="primary wide" disabled={selected.length!==3} onClick={()=>{dispatch({type:'discard',ids:selected});setInspect(null);}}>KEEP THE OTHER TEN</button><p className="hint">Enhancements stay on the shared deck for the night.</p></>}
    {s.phase==='insight'&&<><h3>A name appears in the margin.</h3><p>Keep the Veiled card’s invitation: +1 Insight. At 3, your first marked capture earns +2 Mult, but failed bids cost 2 extra Composure.</p><div className="actions"><button onClick={()=>dispatch({type:'insight',accept:false})}>Leave it unread</button><button className="primary" onClick={()=>dispatch({type:'insight',accept:true})}>Read it · +1</button></div></>}
    {s.phase==='play'&&ourTurn&&<><div className="play-hint">{picked?<><strong>{cardName(picked)}</strong>{picked.mod?` · ${MODIFIERS[picked.mod].effect}`:' · Ready to play'}{trump&&picked.rank===11&&picked.suit!==trump&&effective(picked,trump)===trump?` · Left bower: ${suitName(trump)}`:''}</>:s.plays.length?`Follow ${suitName(effective(s.plays[0].card,trump!))} if you can. Dim cards cannot be played.`:'Lead any card. Tap to select, then play.'}</div><button className="primary wide" disabled={!picked||!playable.some(c=>c.id===picked.id)} onClick={()=>{dispatch({type:'play',id:picked!.id});setInspect(null);}}>PLAY {picked?cardName(picked):'A CARD'}</button></>}
    {s.phase==='trick'&&<><p>{s.plays.map(p=>`${seatName(p.seat)} ${cardName(p.card)}`).join(' · ')}</p><button className="primary wide" onClick={()=>dispatch({type:'collect'})}>{s.history.length===9?'FINISH THE DEAL':'NEXT TRICK'}</button></>}
    {!ourTurn&&['auction','play','kitty'].includes(s.phase)&&<><p>{seatName(s.turn)} is {s.phase==='auction'?'considering the bid':s.phase==='kitty'?'choosing discards':'choosing a card'}…</p><p className="hint">You can inspect both your hands while you wait.</p></>}
    <div className="table-tools"><button onClick={()=>setModal('history')}>Auction & tricks</button><button onClick={()=>setModal('rules')}>House rules</button></div>
   </section>
  </>}
  {s.phase==='settlement'&&<section className="settlement"><p className="eyebrow">DEAL {s.deal} · {s.bid!.tricks}{symbol(trump!)} BY {seatName(s.bid!.seat).toUpperCase()}</p><h2>{s.message||'Counting the tricks…'}</h2><div className="big-score">+{compact(s.dealScore)}</div><p>{s.points} points × {s.mult} Mult{s.ledger.some(e=>e.factor)?' × 2 exact bid':''}</p><div className="result-facts"><span>You took <b>{s.tricks[0]} tricks</b></span><span>{s.penalty?`−${s.penalty} Composure`:'Composure held'}</span><span>Night score <b>{compact(s.score)}</b></span></div><Ledger s={s}/><button className="primary wide" disabled={!s.counters.settled} onClick={()=>dispatch({type:'pub'})}>{s.composure<=0||s.deal>=3?'END THE NIGHT':'VISIT THE PUB'}</button></section>}
  {s.phase==='pub'&&<section className="pub"><p className="eyebrow">BETWEEN DEALS · £{s.cash} TO SPEND</p><h2>A little company.</h2><p className="muted">Recruit a Regular, change the deck, then get some air.</p><div className="shop-list">{s.offer.map(id=>{const r=regular(id);return <article key={id} className="shop-item"><Portrait id={r.portrait}/><div><h3>{r.name}</h3><p>{r.effect}</p><button className="brass" disabled={s.cash<r.price||s.regulars.length>=5} onClick={()=>dispatch({type:'buy',id})}>Recruit · £{r.price}</button></div></article>;})}{!s.offer.length&&<p>The others have gone back to their tables.</p>}</div>
   <details className="deck-tools"><summary>The shared deck · enhance & favour</summary><p>Rivals can receive your enhanced cards. Favour one to make it more likely to reach your partnership next deal; the kitty can still take it.</p><label>Physical card<select value={enhanceId} onChange={e=>setEnhanceId(e.target.value)}>{s.deck.map(c=><option key={c.id} value={c.id}>{cardName(c)}{c.mod?` · ${MODIFIERS[c.mod].name}`:''}</option>)}</select></label><label>Enhancement<select value={enhanceMod} onChange={e=>setEnhanceMod(e.target.value as Modifier)}>{Object.entries(MODIFIERS).map(([id,m])=><option key={id} value={id}>{m.name}</option>)}</select></label><p>{MODIFIERS[enhanceMod].effect}</p><button disabled={s.cash<3||s.enhanced} onClick={()=>dispatch({type:'enhance',id:enhanceId,mod:enhanceMod})}>{s.enhanced?'Enhancement used this visit':'Enhance this card · £3'}</button><button onClick={()=>dispatch({type:'favour',id:enhanceId})}>Favour this card · free</button><p>Favoured: <strong>{s.favour?cardName(s.deck.find(c=>c.id===s.favour)!):'None'}</strong>{s.favour&&<button className="text-button" onClick={()=>dispatch({type:'favour',id:null})}>Clear</button>}</p></details>
   <div className="courtyard"><p className="eyebrow">THE COURTYARD</p><h3>{campaign.metMabel?'Mabel kept the chair.':'Mabel moves a chair for you.'}</h3><p>{campaign.metMabel?'“You asked about the other door.” She looks at the wall. “It used to open.”':'“That door wasn’t there last week,” she says. There is a perfectly ordinary wall where she points.'}</p>{!s.eventDone?<><button onClick={()=>chooseEvent('rest')}>Sit with her · recover 3 Composure</button><button onClick={()=>chooseEvent('ask')}>Ask about the door · +2 Insight</button><p className="hint">At Insight 3: first marked capture +2 Mult; failed bids cost 2 extra Composure. This lasts all night.</p><button className="text-button" onClick={()=>chooseEvent('leave')}>Return inside · no change</button></>:<p className="event-complete">{s.insight>=3?'Inside, the portraits have turned a little towards your table.':'For a moment, the rain is all you can hear.'}</p>}</div><button className="primary wide" disabled={!s.eventDone} onClick={()=>{dispatch({type:'next'});setInspect(null);}}>DEAL {s.deal+1} →</button>
  </section>}
  {s.phase==='over'&&<section className="night-end"><p className="eyebrow">{s.composure>0?'LAST ORDERS':'TIME TO GO HOME'}</p><h2>{s.composure>0?'They’ll keep your seat.':'Enough for one night.'}</h2><div className="big-score">{compact(s.score)}</div><p>points across {s.deal} {s.deal===1?'deal':'deals'}</p><p>{s.composure} Composure · {s.insight} Insight · {s.regulars.length} Regulars</p><p className="muted">{campaign.metMabel?'Mabel will remember the conversation. The deck starts fresh next night.':'The pub will be here tomorrow. Probably.'}</p><div className="result-facts"><span>Best night <b>{compact(Math.max(campaign.best,s.score))}</b></span></div><button className="primary wide" onClick={()=>startNew()}>ANOTHER NIGHT</button><button className="wide" onClick={exportSave}>Export this night for feedback</button><button className="text-button" onClick={()=>startNew(true)}>Replay this seed</button></section>}
  </>}
  <footer className="club-footer"><span>{s.insight>=3?'AFTER HOURS':'CLOSING TIME'}</span><span>Seed {s.seed}</span></footer>
  {modal&&<Modal title={regularId?regular(regularId).name:modal.startsWith('card:')?'Card detail':({menu:'Your night',rules:'House rules',history:'The table’s record',ledger:'Score ledger',insight:'The price of seeing',composure:'Keep your nerve',restart:'Leave this night?'}[modal]??'The club')} onClose={()=>setModal(null)}>
   {regularId&&<><Portrait id={regular(regularId).portrait} className="detail-portrait"/><p className="tag">{regular(regularId).tag}</p><p>{regular(regularId).effect}</p><p className="muted">Regulars belong to your partnership for this night.</p></>}
   {modal.startsWith('card:')&&(()=>{const c=s.hands.flat().find(c=>c.id===modal.slice(5));return c?<><CardFace card={c} trump={trump}/><p>{cardName(c)}{c.mod?` · ${MODIFIERS[c.mod].name}`:''}</p><p>{c.mod?MODIFIERS[c.mod].effect:'An ordinary card in an unusual place.'}</p>{trump&&effective(c,trump)===trump&&<p>Counts as trump: {suitName(trump)}.</p>}</>:null;})()}
   {modal==='composure'&&<><p>Keep your nerve. At zero, your night ends.</p><p>Failing your bid costs 2 Composure at six tricks, then 2 more per extra trick. If rivals make theirs, lose 1 at six tricks, plus 1 per extra trick.</p><p>Insight 3 adds 2 to your failed-bid penalty. Sitting with Mabel restores 3, up to 20.</p></>}
   {modal==='insight'&&<><p>Insight {s.insight} / 3 · {s.insight>=3?'The room remembers.':'The pub still looks almost ordinary.'}</p><p>At 3, your first captured trick containing a marked card adds <b>+2 Mult</b>. Veiled cards become worth 15 points when captured.</p><p>The cost: your failed bids lose <b>2 extra Composure</b>. Your Listener Regular also wakes up, if recruited.</p><p>Insight is optional and resets each night. Ordinary play does not increase it.</p></>}
   {modal==='rules'&&<Rules/>}
   {modal==='ledger'&&<><p>Pending: {s.points} points × {s.mult} Mult. Contract and exact-bid bonuses resolve after all ten tricks.</p><Ledger s={s}/></>}
   {modal==='history'&&<><h3>Auction</h3><ol>{s.auction.map((a,i)=><li key={i}>{a}</li>)}</ol><h3>Tricks</h3>{s.history.map((t,i)=><p key={i}><b>{i+1}. {seatName(t.winner)} wins</b><br/>{t.plays.map(p=>`${seatName(p.seat)} ${cardName(p.card)}`).join(' · ')}</p>)}{!s.history.length&&<p>No completed tricks yet.</p>}</>}
   {modal==='menu'&&<><p className="muted">First sitting · v0.1 · Suited 500</p><button className="wide" onClick={()=>setModal('rules')}>House rules</button><label className="speed"><input type="checkbox" checked={speed} onChange={e=>setSpeed(e.target.checked)}/> Faster rival turns</label><button className="wide" onClick={exportSave}>Export save & replay</button><button className="wide" disabled={busy} onClick={()=>fileRef.current?.click()}>Import save</button><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{if(file.size>500000)throw new Error('Save is too large.');const data=unpack(await file.text());setS(data.state);setCampaign(data.campaign);setInspect(null);setSelected([]);setModal(null);}catch(err){setError(err instanceof Error?err.message:'Could not import save.');}finally{setBusy(false);e.target.value='';}}}/><button className="wide" onClick={()=>setModal('restart')}>Start a fresh night</button><p className="footer-note">Saved on this device. Audio is off in this first prototype. Best score: {compact(campaign.best)}.</p></>}
   {modal==='restart'&&<><p>Your current night will be replaced. Your best score and Mabel’s memory stay.</p><button className="wide" onClick={exportSave}>Export this night first</button><button className="primary wide" onClick={()=>startNew()}>Start a fresh night</button></>}
  </Modal>}
 </main>;
}
function Ledger({s}:{s:State}) {return <div className="ledger">{s.ledger.length?s.ledger.map((e,i)=><div key={i}><span>{e.label}</span><strong>{e.points?`+${e.points} pts`:e.mult?`+${e.mult} Mult`:`×${e.factor}`}</strong></div>):<p>No points yet. Win a trick to open the ledger.</p>}</div>;}
function Rules(){return <div className="rules"><p><b>You control South and North</b> against Arthur and Mabel. Highest bidder takes the three-card kitty, discards three, and leads. Win at least the number of tricks you promised.</p><h3>The auction</h3><p>Bid 6–10 tricks. Suits rise ♠, ♣, ♦, ♥. Seven spades beats six hearts. Once you pass, you cannot re-enter. If everyone passes, the dealer takes six spades. This is our provisional all-pass house rule.</p><h3>The cards</h3><p>43 cards: no twos, threes or black fours, plus one joker. Follow the led suit if you can. If you cannot, play any card.</p><p><b>Trump order:</b> joker, jack of trump (right bower), jack of the other same-colour suit (left bower), ace, king, queen, then numbers. The left bower belongs to trump, including for following suit.</p><p>Highest trump wins. With no trumps, highest card in the led suit wins. The winner leads next. You play all ten tricks.</p><h3>Bidding or defending</h3><p>Each trick you capture adds 10 points. Make your contract for its displayed bonus. If rivals declare, stop them reaching their bid to earn the same base bonus. Regulars and marked cards add points and Mult.</p><p>Score = (trick points + card effects + earned contract/set bonus) × Mult × exact-bid effects. Failing a contract still costs Composure, even if you scored well.</p><h3>Our first sitting</h3><p>Three deals, eight Regulars, four card enhancements and one Insight threshold. No-trump and misère are not in this slice. There is no room score gate yet: survive, build combinations and compare your score.</p><p>Rivals see their own hand and public plays only. Your two hands are visible to you. Opponent difficulty and the economy are provisional.</p><p>Shared-deck enhancements can land in any hand. The kitty always contains at least one. Favouring a card increases its chance of reaching your partnership; it never guarantees it.</p></div>;}
